name: casino_test
description: Casino test application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localization: any
  get_it: ^7.2.0
  http: ^0.13.4
  intl: any
  json_annotation: ^4.4.0
  shared_preferences: ^2.1.1

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/


#       name: casino_test
# description: Casino test application

# publish_to: 'none'

# version: 1.0.0+1

# environment:
#   sdk: ">=2.13.4 <3.0.0"
#   flutter: ">=1.17.0"

# dependencies:
#   flutter:
#     sdk: flutter
#   get_it: ^7.2.0
#   flutter_bloc: ^8.0.1
#   equatable: ^2.0.3
#   http: ^0.13.4
#   json_annotation: ^4.4.0
#   cupertino_icons: ^1.0.2

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   build_runner: ^2.0.0
#   json_serializable: ^6.0.0
#   flutter_lints: ^1.0.0

# flutter:
#   uses-material-design: true